settings:
  title: 'Състояние на инфраструктурата на chitanka.info'
  url: 'https://status.chitanka.info' # used for Slack messages
  logo: logo.120px.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: '✔ Всичко работи'
  notAllmonitorsOperational: '✘ Не всичко работи'
  monitorLabelOperational: '✔ Работи'
  monitorLabelNotOperational: '✘ Не работи'
  monitorLabelNoData: 'Няма данни'
  dayInHistogramNoData: 'Няма данни'
  dayInHistogramOperational: 'Всичко е наред'
  dayInHistogramNotOperational: ' инцидент(а)' # xx incident(s) recorded

monitors:
  - id: chitanka-info
    name: chitanka.info
    description: 'Библиотеката'
    url: 'https://chitanka.info'
    method: GET
    expectStatus: 200

  - id: biblioman-chitanka-info
    name: biblioman.chitanka.info
    description: 'Библиоман'
    url: 'https://biblioman.chitanka.info'
    method: GET
    expectStatus: 200

  - id: forum-chitanka-info
    name: forum.chitanka.info
    description: 'Форум'
    url: 'https://forum.chitanka.info'
    method: GET
    expectStatus: 200

  - id: chat-chitanka-info
    name: chat.chitanka.info
    description: 'Чат'
    url: 'https://chat.chitanka.info'
    method: GET
    expectStatus: 200
