settings:
  title: 'Състояние на инфраструктурата на chitanka.info'
  url: 'https://status.chitanka.info' # used for Slack messages
  logo: logo.120px.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: '✔ Всичко работи.'
  notAllmonitorsOperational: '✘ Не всичко работи.'
  monitorLabelOperational: '✔ Работи'
  monitorLabelNotOperational: '✘ Не работи'
  monitorLabelNoData: 'Няма данни'
  dayInHistogramNoData: 'Няма данни'
  dayInHistogramOperational: 'Всичко е наред'
  dayInHistogramNotOperational: ' инцидент(а)' # xx incident(s) recorded

monitors:
  - id: chitanka-info
    name: chitanka.info
    description: 'Библиотеката'
    url: 'https://chitanka.info'
    method: GET
    expectStatus: 200

  - id: biblioman-chitanka-info
    name: biblioman.chitanka.info
    description: 'Библиоман'
    url: 'https://biblioman.chitanka.info'
    method: GET
    expectStatus: 200

  - id: forum-chitanka-info
    name: forum.chitanka.info
    description: 'Форум'
    url: 'https://forum.chitanka.info'
    method: GET
    expectStatus: 200

  - id: chat-chitanka-info
    name: chat.chitanka.info
    description: 'Чат'
    url: 'https://chat.chitanka.info'
    method: GET
    expectStatus: 200

  - id: prevodi-chitanka-info
    name: prevodi.chitanka.info
    description: 'Дачко'
    url: 'https://prevodi.chitanka.info'
    method: GET
    expectStatus: 200

  - id: rechnik-chitanka-info
    name: rechnik.chitanka.info
    description: 'Речник'
    url: 'https://rechnik.chitanka.info'
    method: GET
    expectStatus: 200

  - id: rbe-chitanka-info
    name: rbe.chitanka.info
    description: 'Версия на РБЕ'
    url: 'https://rbe.chitanka.info'
    method: GET
    expectStatus: 200

  - id: gramofonche-chitanka-info
    name: gramofonche.chitanka.info
    description: 'Грамофонче'
    url: 'https://gramofonche.chitanka.info'
    method: GET
    expectStatus: 200

  - id: smehurko-chitanka-info
    name: smehurko.chitanka.info
    description: 'Смехурко'
    url: 'https://smehurko.chitanka.info'
    method: GET
    expectStatus: 200

  - id: tools-chitanka-info
    name: tools.chitanka.info
    description: 'Работни инструменти'
    url: 'https://tools.chitanka.info'
    method: GET
    expectStatus: 200

  - id: planet-chitanka-info
    name: planet.chitanka.info
    description: 'Събирателно място за читателски блогове'
    url: 'https://planet.chitanka.info'
    method: GET
    expectStatus: 200

  - id: api-chitanka-info
    name: api.chitanka.info
    description: 'API за обновяване на огледалата'
    url: 'https://api.chitanka.info'
    method: GET
    expectStatus: 200

  - id: assets-chitanka-info
    name: assets.chitanka.info
    description: 'Статични файлове на библиотеката'
    url: 'https://assets.chitanka.info'
    method: GET
    expectStatus: 200

  - id: download-chitanka-info
    name: download.chitanka.info
    description: 'Файлове за сваляне'
    url: 'https://download.chitanka.info'
    method: GET
    expectStatus: 200

  - id: puk-chitanka-info
    name: puk.chitanka.info
    description: 'Копие на проекта ПУК!'
    url: 'https://puk.chitanka.info'
    method: GET
    expectStatus: 200

  - id: wiki-chitanka-info
    name: wiki.chitanka.info
    description: 'Старото уики'
    url: 'https://wiki.chitanka.info/%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BD%D0%B0_%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0'
    method: GET
    expectStatus: 200
